### ISSUE TITLE
Difficulty Accessing Quill Editor Instance for Custom JavaScript Integration

### ISSUE THREAD

**Issue by Gatos90** [fgilde/MudExRichTextEditor#2]
I am working on integrating custom JavaScript functionality with the Quill editor within a Blazor application.
I've encountered challenges accessing the Quill editor instance from my own JavaScript functions to inject custom logic.
There seems to be a scope issue or a misunderstanding on my part regarding how to maintain a reference to the Quill instance for use across different parts of the application.
Can U Help me here?

**Comment by fgilde** [comment]
I can try. 

In generell the `MudExRichTextEdit` provides the ElementReference where quill is created from. With this reference you can pass it to your javaScript with the IJSRuntime as an argument.

```c#
@using BlazorJS
@inject IJSRuntime JsRuntime

<MudExRichTextEdit  @ref="_richTextEditor">

</MudExRichTextEdit>

<MudButton OnClick="@(StoreQuill)">Store to window.QuillEditor</MudButton>


@code {
   private MudExRichTextEdit _richTextEditor;

   private async Task StoreQuill()
   {
        await _js.DInvokeVoidAsync((window, quill) => window.QuillEditor = quill.__quill, _richTextEditor.ElementReference);
   }
}
```` 

Here in this sample after the button is clicked, the quill reference is available under window.QuillEditor . You can invoke your code or whatever instead of simply pass it to an window object.

**Comment by fgilde** [comment]
Please let me know if this helps or you need more info.
