### ISSUE TITLE
Mentions

### ISSUE THREAD

**Issue by americanslon** [fgilde/MudExRichTextEditor#4]
First off GJ!
Nice clean control, already better than the halfassed tinymce wrapper that tinymce hasn't bother to update in a year and a half.

Couple of things about mentions.

1. The mention container shows up inside the editor only. If you have a short editor or a long list, both are true in my case, it's essentially unusable. I tried playing around with z-index on various layers of the editor but nothing seems to work. 
2. Is it possible for the mentions to have different display value from data value? I'd like to be able to use the mentions to link to different entities of my app so I'd like the display text be something user readable but the value be Id (or the whole object) that I use to redirect users on `MentionClicked`.
3. Is it possible to add multiple mention module defenitions? I got it to compile by doing the following

```
        List<IQuillModule> b = new List<IQuillModule>();
        b.Add(new QuillMentionModule<Domain.User.User>((c, s) => Task.FromResult(users.Where(user => user.DisplayNameTitle.Contains(s, StringComparison.InvariantCultureIgnoreCase))), '@').SetProperties(m => m.MentionClicked = UserMentionClicked));
        b.Add(new QuillMentionModule<Domain.Lab.Lab>((c, s) => Task.FromResult(labs.Where(lab => lab.Name.Contains(s, StringComparison.InvariantCultureIgnoreCase))), '#').SetProperties(m => m.MentionClicked = LabMentionClicked));

        modules = b.ToArray();
```

but that doesn't work. It doesn't break, no runtime errors, but it just seems to completely disable the mention functionality.

Thanks!

**Comment by fgilde** [comment]
I will have a look on it

**Comment by fgilde** [comment]
Ok part3 is done and multiple mentionmodules can be used now. in version 1.0.5 
[Nuget MudExRichTextEditor 1.0.5](https://www.nuget.org/packages/MudExRichTextEditor/1.0.5)

You can see the how to use in the [Example Project](https://github.com/fgilde/MudExRichTextEditor/tree/master/Example) its used there in the [index page](https://github.com/fgilde/MudExRichTextEditor/blob/master/Example/Pages/Index.razor)


For point number 2 you can currently override the ToString() method in you c# class. But in general I plan to support DisplayMember and an ItemTemplate, but because mentions in general is an external module is hard to do and a lot of work.

And finally for Point 1 please create a new issue for that. Not sure if I can solve it becaused mentions is an external complex module and again hard to do and a lot of work. In generell you need to set the position to fixed and add a margin-left and a margin-top based on the editor position to solve it.
